x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
  AIRFLOW__CORE__STORE_SERIALIZED_DAGS: "True"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "True"
  # IMPORTANTE AIRFLOW 3
  AIRFLOW__CORE__INTERNAL_API_SECRET_KEY: "mi_clave_super_secreta_123"
  AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution"
  AIRFLOW__WEBSERVER__SECRET_KEY: "una_clave_secreta_muy_larga_y_segura"
  AIRFLOW__CORE__FERNET_KEY: "46BKJoQYlPPOexq0OhDZnIlUkKD3NvZIvIItJ1g34Ew="
  # NUEVA VARIABLE OBLIGATORIA PARA EL TASK SDK DE AIRFLOW 3
  AIRFLOW__API_AUTH__JWT_SECRET: "una_clave_jwt_super_secreta_y_larga_para_airflow_3"
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
  MLFLOW_S3_ENDPOINT_URL: "http://s3:9000"
# Definición de los servicios (contenedores) que componen la infraestructura
services:

  # 1. Base de Datos Postgres: Almacena los metadatos de MLflow (experimentos, parámetros, etc.)
  postgres:
    build: './dockerfiles/postgresql'
    image: postgres_operaciones_maquina
    container_name: postgres
    networks:
      - backend # Conexión a la red privada para comunicarse con mlflow
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432" # Expone el puerto para acceso externo si fuera necesario
    volumes:
      - db_data:/var/lib/postgresql/data # Persistencia: los datos no se borran al reiniciar el contenedor
    healthcheck:
      test: [ "CMD", "pg_isready", "-p", "5432", "-U", "airflow" ]
      interval: 60s
      timeout: 20s
      retries: 3

  # 2. Almacenamiento S3 (MinIO): Donde se guardan los modelos y artefactos pesados
  s3:
    image: minio/minio:latest
    container_name: minio
    networks:
      - backend
    ports:
      - "9000:9000" # API para subir/bajar modelos
      - "9001:9001" # Consola web de gestión de MinIO
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio_data:/data # Persistencia: donde se guardan los archivos físicamente
    command: server /data --console-address :9001

  # 3. Inicializador de S3: Automatiza la creación de buckets para MLflow y datos
  create_s3_buckets:
    image: minio/mc:latest
    networks:
      - backend
    depends_on:
      - s3
    volumes:
    # Conectamos la carpeta local 'data' con la carpeta '/local_data' del contenedor
      - ./data:/local_data
    entrypoint: >
      /bin/sh -c ' 
      echo "Esperando a que MinIO esté listo...";
      until (/usr/bin/mc alias set s3 http://s3:9000 minio minio123); do sleep 2; done;
      /usr/bin/mc alias set s3 http://s3:9000 minio minio123; 
      /usr/bin/mc mb --ignore-existing s3/mlflow; 
      /usr/bin/mc mb --ignore-existing s3/data; 
      /usr/bin/mc mb --ignore-existing s3/data/raw;
      /usr/bin/mc mb --ignore-existing s3/data/processed;
      echo "Subiendo dataset crudo a MinIO...";
      /usr/bin/mc cp /local_data/healthcare-dataset-stroke-data.csv s3/data/raw/healthcare-dataset-stroke-data.csv;
      echo "Aprovisionamiento completado.";
      exit 0; 
      '

  # 4. Cola de Mensajes Redis: Coordinación entre servicios
  redis:
    image: valkey/valkey:8.1-bookworm
    container_name: redis
    expose:
      - "6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  # 5. Servidor de MLflow: Interfaz para gestionar experimentos de ML
  mlflow:
    build: "./dockerfiles/mlflow"
    container_name: mlflow
    networks:
      - backend
    ports:
      - "5000:5000"
    command: >
      --host 0.0.0.0  --port 5000  --backend-store-uri postgresql://airflow:airflow@postgres:5432/mlflow_db --default-artifact-root s3://mlflow/
    depends_on:
      postgres:
        condition: service_healthy # MLflow arranca solo cuando Postgres está listo
      create_s3_buckets:
        condition: service_completed_successfully
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      # URL donde MLflow guarda la información estructurada
      - MLFLOW_BACKEND_STORE_URI=postgresql://airflow:airflow@postgres:5432/mlflow_db
      # URL donde MLflow guarda los archivos físicos
      - MLFLOW_ARTIFACT_ROOT=s3://mlflow/
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000

  # 6. Inicializador de Airflow: Automatiza la configuración inicial de Airflow
  airflow-init:
    build: ./dockerfiles/airflow
    container_name: airflow-init
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    command: airflow db migrate
    environment:
      <<: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  # 7. ApiServer de Airflow: Interfaz de usuario para gestionar flujos de trabajo
  airflow-apiserver:
    build: ./dockerfiles/airflow
    container_name: airflow-apiserver
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      <<: *airflow-env
    command: airflow api-server
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  # 8. Scheduler de Airflow: Orquesta la ejecución de los flujos de trabajo
  airflow-scheduler:
    build: ./dockerfiles/airflow
    container_name: airflow-scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - backend
    environment:
      <<: *airflow-env
    command: airflow scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  # 9. Procesador de DAGs de Airflow: 
  airflow-dag-processor:
    build: ./dockerfiles/airflow
    container_name: airflow-dag-processor
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - backend
    environment:
      <<: *airflow-env
    command: airflow dag-processor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  # 10. Worker de Airflow: Procesador de tareas distribuidas
  airflow-worker:
    build: ./dockerfiles/airflow
    container_name: airflow-worker
    restart: always

    depends_on:
      airflow-init:
        condition: service_completed_successfully

      redis:
        condition: service_healthy

    networks:
      - backend

    environment:
      <<: *airflow-env

    command: airflow celery worker

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  # 11. Servicio de Predicción (FastAPI): API para servir modelos entrenados
  fastapi:
    build: ./dockerfiles/fastapi
    container_name: fastapi
    restart: always
    ports:
      - "8800:8800"
    networks:
      - backend
    depends_on:
      - mlflow # La API consultará a MLflow para obtener modelos
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
# Definición de la red (puente) que permite la comunicación entre contenedores
networks:
  backend:
    driver: bridge

# Definición de volúmenes persistentes (almacenamiento en disco local)
volumes:
  db_data: # Espacio de Postgres
  minio_data: # Espacio de MinIO
