[project]
name = "tp-operecionnes-maquina-i"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow-providers-amazon>=9.29.0",
    "apache-airflow-providers-postgres>=6.7.0",
    "boto3>=1.43.18",
    "mlflow>=3.12.0",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.12",
    "scikit-learn>=1.8.0",
]
